apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path # k3s 기본 프로비저너 (노드 디스크)
  resources:
    requests:
      storage: 1Gi
