---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-admin
  namespace: blog
spec:
  encryptedData:
    ADMIN_PASSWORD_HASH: AgBTGT0tPpKWXzs87DIAi817XxqTjnMACuXrq7mLXgKHf7067Rzq0bvtaAzr4JbRlWSpCezT36ULuV19J6OqmrEuq886FxMslleKPhUh7fpwC5TIbC1k0xF7Nq7Zi4QmTNcWoMuHhzjdn+JLbwbWinQqDScCBO2U3P3IG3r/g+bYb93HCpuF3nXa0d3ESdwZWvRAaS71YXXpmZzzbqG5jSu4Q1PUpAz6gr7R53vnt1e0FHzZ5IB3n7HCZl1XUlG4YOYGdF7HJpV59nwA2KwxrWVmy4aU8J3eHdn5DJdDziewb3bw8q6Tqu/gpfr5N5tNesYN/2SohbLvnOCfRJmlykTQ8nIxIswOpXYMe+1gZrStZN6lSOz5JSBJ2esy4TmV/WsgRQgYDJhtMmKKp2lTtXvOqSnGYNXNOpqu0nhS6/+y4RXzXa54GJ/xafF0QSmtEF0M/y5mDa4kYsaMCUoTuFxNgD6quaWytCLK1T6oCDtTqfx/OECd5O3OA7JX0yG6RILh3Dm5AqEeLaLc89ldNpObG5x3i0x3gIQrnQn5AhqzUL7j8JqVr6pRX3RVdAAA5xDnJq2clIdJhFWzrDWICP2YvMb36L/izRIu7uprWvkoUb7aCC3D4UhUxhFSE2d/oHa9RUcNyn66+IwfCiS/Ur0P1saLJAtBbrhYLI8j6oy9Q1fd1MuGod/f8wpy4TjvJvawYSGOTt11fhFPJuU3RDsCjutHw1YDhYVIeOVelXfjco2L97l14Zi+I4tWLJk1mTD9QIZe8qgWwqa51NA=
    AUTH_SECRET: AgBIngeXcyq6ZlGBMCkarhZSZZ3/FWG29C/gzEd11MfrYPBgC4W4xVExQy0AqTV0330FOBrNyugBZShrEogLBMwNS9wAxGSspjASz9ZhGUEswD2RjyCKJsQ9i9+X82GUr994uVy/QnF+/hzxBMpTuCT9H3RMlhIzemCEXwGLVMgnR6sc9r2dJ5c8tpHkSTp3ETS/1yS9wZtIHRi3KJXXbNS59/CHFitpjORmePOgLL2KrZ6DHC2igdslFPqeRCGvIvCXyEa4xxtTbMFJT2nUbxtVi2qaWcdsCOqexxHHPZuLKbCHI7IykTE6HLhfJq31eGrrL5x+sUDFc4F0HgcsUTdItP9/rFQarYzpToCpVzKV0+u3VZT5LpCArOF1WmhNUX3S8wqEHuek9lpeTrN1hlW7EybrA24Y0JT8bh9HCHs+tJFv5YSWnTtOVXjGXmxfWVVJy/eqIQV3J9YSeHYUwVK9XXYchoB9XiMzzVPtWzkyMUfUqgmWqsjav5XrwOLFtBVVm256x5i9yiXpDNKelkz2elUfOOLFP4Sd8O3iAr/VOT4Inw/k553nZHE4GFZ9KqHBOm548V0yTUaReUrZQbU3LBZDygclDWGI65UXGH69lXt/xgpnkQYAaK9TATU8c3Ce2nuaVfp0PjgYi+GKmDZ9zo3PUitvhi0t2c3pkI/M3b4hY1QXvQKopiP76v0loqlgwF/s295mqJCKQ3ZNtfcGynbt+BrbJ/krButpmB0pt5gKS4VHrfJd4qhkwKAj7+4pzWjUrfnfrMHfq40Q0NTV
  template:
    metadata:
      name: blog-admin
      namespace: blog
    type: Opaque
