apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: blog
spec:
  encryptedData:
    token: AgCa6BmZLwPiehuJIp1FguE+ohpR3jqwCeA6RyRQTrlxPE5qRunBLR8a/U3utI7+xi+i1z8vIcMAgkQGYDvVGiwcn6uu79Wv1UCwjLxuyg15i2IW7tkdZmukSbUI+M6A/1F99vnE0ReJjkmKKsIOpgx9t0pWpVoWufQptl4b3s4vtfVHMoJjs+Uy0msdoWoiUdqqRBPkyL9TpBHSqs7Q5SPciLDMton6zZpQRszOopIMID7dYUML4IpzCjS+bzRBoMGKlXBbkIMfnSRxJrdXQyNeYS/SjBH0nRuE+zOWVC5RCT5Pj3nsO3/9ERKRFEUfTOcJU80Q73UPaHxT4woxYudeCH/zcGlJb5fO9IYz2A0dgfhp9qYyiufmUPoLHQdwbkNgA8JlEdot9zAN5nN9rJt6iUfW56VaiUqe1UgK3S6ymbcEh7+KHEleEmkGXw1fq479TuEwXrBe1iYNVEJtEhGE6fbZGVFNTlQhilo4CSuOJ3KFv5T/9BnQr/IZ6P5o308kTMHRPAysfBmyoZWuCKbPzdoX4CSUrYlpKmPrNTxLq+t4VeqSPaK4B4EHWyf3JrECXCUT2OtHcojdwL9KxsIbXK2AGkGwkQvm9rESbNH7N/3w36tYhH8nwVzqTCnLC1Up4aHsX/+P8SPbmADVXMNcs2/ZSySflTod1SS0Ak100tl+laXeOXdI/f5PVLwLAo4HzvN0D/sFn63amej13krtynSddwndnFoF65d98Ooj2ltfeXnQUaJugkjKy7+dkMApX+iB53CMrjRnMt1AB9lsaJZL1/aZVO2lQ88FLvkYWrqEVZxtajAurUJDd1/OzeSBaj7xbXd/ekLJzVeX7Q6jOKRP8ay2ZPJ8s48ySPglphcbAP04v2yDnh+khKBvuOomTMPeDqh/TUgXUGIFRMom/BrskwTbu42iP1TnfdJMdZpKlx5AD9yb
  template:
    metadata:
      name: cloudflared-token
      namespace: blog
    type: Opaque
